version: '3.1'

services: 
  database:
    image: 'postgres:latest'

    ports:
      - 5432:5432
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stock_tracker
  
        #  pgadmin:
        #    image: dpage/pgadmin4:4.23
        #    environment:
        #      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
        #      PGADMIN_DEFAULT_PASSWORD: password
        #      PGADMIN_LISTEN_PORT: 80
        #
        #    ports:
        #        - 1543:80 
        #    depends_on:
        #        - database
